nspcc-dev/panel-fs-neo-org

src/Profile.js
=> Move unnamed containers to bottom

README.md
=> Explanations about migration in README

src/Profile.js
=> Withdraw GAS not working

src/App.js
=> Save signed tokens

src/Components/ContainerItem/ContainerItem.js
=> Add loader for objects list

src/App.js
=> Logout on closed websocket connection

src/index.js
=> Change WalletConnectProvider options

src/App.js, src/Components/ContainerItem/ContainerItem.js, src/Components/TreeView/TreeView.js, src/Home.js, src/Profile.js, src/api.js
=> Check REST gw connection

src/App.js
=> Consider tokens lifetimes

Makefile, README.md, help.mk
close #84 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>
=> [#84] Improve Makefile

Makefile, package.json, src/App.js
=> Add website version to the page

.gitignore, Makefile, README.md, package.json
=> Improve Makefile

package.json
=> Webpack Source Map Disclosure

src/App.css
=> Long file names break the interface 

package.json, src/App.js, src/Home.js, src/Profile.js
=> Errors for npm start on node 18

src/App.css, src/App.js, src/Home.js, src/Profile.js
=> pipe must not be a link

package.json
=> Remove package.json vulnerabilities

CHANGELOG.md, package.json
=> Release v0.2.1

README.md
=> Add instruction for starting webapp with AIO in README

src/App.js, src/Home.js, src/Profile.js
=> Endless reloading after connect wallet

Makefile
=> Add profile page in Makefile

CHANGELOG.md, package.json
=> Release v0.3.1

.env, README.md, src/App.js
=> Some variable for wallet network setting

.env, README.md, src/Profile.js
=> Derive scripthash from neo account

package.json
=> Outdated WC SDK 

src/App.css, src/App.js, src/Profile.js, src/api.js
=> Long file name extends beyond the screen

README.md, src/Home.js
=> src: don't mention Aero (it's beta)

src/App.css, src/App.js, src/Components/EACLPanel/EACLPanel.js
closes #146
- Add input caption for strict Basic ACL field
- Move presets to eACL and update it
=> Improve access control section in creation container form

src/App.js, src/api.js
=> Uploading big files never finishes 

src/Components/TreeView/TreeView.js
=> web: Display file size in units instead of bytes

src/App.js
=> Reset the data on the popup when an error occurs

src/Profile.js
=> Add error for wc session expiration

.github/workflows/build.yml
The thing should build fine and we want to auto-attach release tarballs.
=> .github: add build workflow

src/Profile.js
=> Error output in console

README.md, src/App.js, src/Home.js, src/Profile.js
=> Add support for NeoLine

README.md, package.json, src/App.js, src/Home.js, src/Profile.js
=> Add support for O3 wallet

src/App.js, src/Profile.js
=> Redesign deposit and withdraw blocks for UX

src/App.css, src/Components/TreeView/TreeView.js, src/Home.js, src/Profile.js
=> Improve design and UX for mobile

src/App.js, src/Profile.js
=> Improve wallet connection error message

Makefile, src/App.js, src/Getobject.js
=> Shared link needs to be adjusted

src/App.css, src/App.js, src/Components/TreeView/TreeView.js, src/Getobject.js, src/Home.js, src/Profile.js
=> UI corrections

src/App.js, src/Home.js
=> Handle "I don't have a wallet" more gracefully

src/App.css, src/Components/EACLPanel/EACLPanel.js
=> Reorder filters/rules in EACLs

src/App.js
=> Incorrect message for links to open containers

src/App.js, src/Getobject.js, src/Home.js, src/Profile.js
=> Implement hosting caption

src/App.js
=> Add a note about container creation cost

public/index.html
=> Application background is not the same theme

src/App.js, src/Components/ContainerItem/ContainerItem.js, src/Components/EACLPanel/EACLPanel.js, src/Components/TreeView/TreeView.js, src/Functions/handle.js, src/Getobject.js, src/Profile.js, src/api.js
=> web: Switch to new REST object APIs

src/App.js, src/Home.js
=> Autodetect Neoline

src/App.css, src/App.js
=> Show direct explorer link in popup, 

src/App.css, src/Profile.js
=> Align balances on decimal point

src/App.js
=> Allow setting GET token lifetime

CHANGELOG.md, package.json
=> CHANGELOG: release 0.7.0
